version: '3'
    
services:
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'axioma'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_HOST: 'db'
            MYSQL_PORT: 3306
    web:
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
